server:
  port: 8080
  servlet:
    context-path: /redis-cache
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cache-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #cache:
    #type: redis
    #redis:
      #time-to-live: 600000 #缓存有效时间，单位毫秒，默认长久有效
      #key-prefix: redis-cache_ #key前缀
      #use-key-prefix: true #在写入Redis时是否要使用key前缀
      #cache-null-values: true #是否允许null值



