#系统公共配置
server:
  port: 8001
  servlet:
    context-path: /utils
  error:
    path: /app/error
spring:
  profiles:
    include:
    - config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/utils_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB