server:
  port: 8080
spring:
  rabbitmq:
    host: 139.159.177.48
    port: 5672
    username: zhaolei
    password: zhaolei
    virtual-host: /
    publisher-returns: true
    #必须配置这个才会确认回调
    publisher-confirm-type: correlated
    listener:
      type: simple
      simple:
        acknowledge-mode: manual #手动确认
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 3 #启动消费者最大数量
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5
          stateless: false
          #时间策略乘数因子
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms
        default-requeue-rejected: true

