server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mybatis/repository/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sql_hibernate_demo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
      jpa:
        show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5Dialect

