server:
  port: 8080
  servlet:
    session:
      timeout: 3600s
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_jsp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp

auth:
  skip:
    antMatchers:
      /**/favicon.ico,
      /**/*.css,
      /**/*.js,
      /**/*.png,
      /**/*.jpg,
      /**/*.gif,
      /**/*.map,
      /**/*.html,
      /**/*.jsp,
      /error,
      /login_failure,
      /swagger-resources/**,
      /webjars/**,
      /v2/**,
      /swagger-ui.html/**

